# Generated by Django 4.2.5 on 2023-12-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='tblevents',
        ),
    ]
